# Base Url = https://insight-hub-api.vercel.app

### regis user
# POST /api/v1/auth/register/user
# POST http://localhost:3000/api/v1/auth/register/user 
POST https://insight-hub-api.vercel.app/api/v1/auth/register/user
Content-Type: application/json

{
  "email":"suryay@gmail.com", 
  "password":"123123", 
  "nama":"user1",
  "no_hp":"081281821",
  "status":"ok"
}

### Login user
# POST /api/v1/auth/login 
POST https://insight-hub-api.vercel.app/api/v1/auth/login
Content-Type: application/json

{
  "email":"surya@gmail.com",  
  "password": "user12345"
}

### forgot password
POST http://localhost:3000/api/v1/auth/forgotPassword
Content-Type: application/json

{
    "email": "surya@gmail.com"
}


### change password
# POST /api/v1/auth/change-password?token={link email params}
POST http://localhost:3000/api/v1/auth/change-password?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InN1cnlhMTIzIiwiZW1haWwiOiJzdXJ5YUBnbWFpbC5jb20iLCJyb2xlcyI6WyJVU0VSIl0sInByb2ZpbGUiOnsiaWQiOjEsImZpcnN0X25hbWUiOiJzdXJ5YTEyMyIsImxhc3RfbmFtZSI6IkRlZmF1bHQiLCJwcm9maWxlX3BpY3R1cmUiOm51bGwsIm5vX2hwIjoiMDkxODc3MiIsInN0YXR1cyI6IlRJIGVuZ2luZWVyIiwicGljdHVyZUlkIjpudWxsLCJ1c2VySWQiOjF9LCJpYXQiOjE3MTIwNzI1MzcsImV4cCI6MTcxMjE1ODkzN30.fIA9oSeZrQ0OC2TJ4nJOd3ehsx59LSs0p81bqb5diLg
Content-Type: application/json

{
  "password":"user12345",
  "confirm_password":"user12345"
}


### PUT / Update profile tanpa foto
PUT https://insight-hub-api.vercel.app/api/v1/auth/profile/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsIm5hbWUiOiJ1c2VyMSIsImVtYWlsIjoic3VyeWF5QGdtYWlsLmNvbSIsInJvbGVzIjpbIlVTRVIiXSwicHJvZmlsZSI6eyJpZCI6MTMsImZpcnN0X25hbWUiOiJ1c2VyMSIsImxhc3RfbmFtZSI6IkRlZmF1bHQiLCJwcm9maWxlX3BpY3R1cmUiOm51bGwsIm5vX2hwIjoiMDgxMjgxODIxIiwic3RhdHVzIjoib2siLCJwaWN0dXJlSWQiOm51bGwsInVzZXJJZCI6MTN9LCJpYXQiOjE3MTIwNDMyMDUsImV4cCI6MTcxMjEyOTYwNX0.re9r--qGIy6QqcN5fcshdA_FBfHNkwyeL7zKqOMDJTU

{
  "first_name":"surcup", //string
  "status":"pelajar" //strng
}

### PUT / Update profile dengan foto
PUT https://insight-hub-api.vercel.app/api/v1/auth/profile/update
Content-Type: multipart/form-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsIm5hbWUiOiJ1c2VyMSIsImVtYWlsIjoic3VyeWF5QGdtYWlsLmNvbSIsInJvbGVzIjpbIlVTRVIiXSwicHJvZmlsZSI6eyJpZCI6MTMsImZpcnN0X25hbWUiOiJ1c2VyMSIsImxhc3RfbmFtZSI6IkRlZmF1bHQiLCJwcm9maWxlX3BpY3R1cmUiOm51bGwsIm5vX2hwIjoiMDgxMjgxODIxIiwic3RhdHVzIjoib2siLCJwaWN0dXJlSWQiOm51bGwsInVzZXJJZCI6MTN9LCJpYXQiOjE3MTIwNDMyMDUsImV4cCI6MTcxMjEyOTYwNX0.re9r--qGIy6QqcN5fcshdA_FBfHNkwyeL7zKqOMDJTU

{
  "first_name":"surcup",
  "status":"pelajar",
  "profile_picture":"`upload file gambar`"
}


### Delete poto profil
DELETE http://localhost:3000/api/v1/auth/profile-picture
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsIm5hbWUiOiJ1c2VyMSIsImVtYWlsIjoic3VyeWF5QGdtYWlsLmNvbSIsInJvbGVzIjpbIlVTRVIiXSwicHJvZmlsZSI6eyJpZCI6MTMsImZpcnN0X25hbWUiOiJzdXJ5YWN1YWtzIiwibGFzdF9uYW1lIjoiRGVmYXVsdCIsInByb2ZpbGVfcGljdHVyZSI6Imh0dHBzOi8vaWsuaW1hZ2VraXQuaW8vamVuaXJpc2thLzE3MTIwNDM4NDAxNTNfZUJYUTY1NTdILmpwZWciLCJub19ocCI6IjA4MTI4MTgyMSIsInN0YXR1cyI6Im1haGFzaXN3YSIsInBpY3R1cmVJZCI6IjIyM2IyMGU2YzcyOTYwZDY4ZGMwYmYwYjU2ZGEyZDRkNzgwMzNlZjYxMWU5YTRjNzI4ODIxM2NhNmZmZDlhZjMiLCJ1c2VySWQiOjEzfSwiaWF0IjoxNzEyMDcxNjMyLCJleHAiOjE3MTIxNTgwMzJ9.2j6DqgVCtPuGO0etyjwzoolgIeHi2eXxkUM3KhYAWeI


### regis SUPERADMIN
# POST /api/v1/auth/register/su
POST http://localhost:3000/api/v1/auth/register/su
Content-Type: application/json

{
  "email":"supery@gmail.com", 
  "password":"123123", 
  "nama":"superapaansi"
}

### Login SUPER ADMIN
# POST /api/v1/auth/login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "supery@gmail.com", 
  "password": "123123"
}



### regis admin
# POST /api/v1/auth/register/admin
POST http://localhost:3000/api/v1/auth/register/admin
Content-Type: application/json
# Authorization: Bearer <token didapat saat login dengan superUser dan token akan nonAktif > 1 days
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6InN1cGVyYXBhYW5zaSIsImVtYWlsIjoic3VwZXJ5QGdtYWlsLmNvbSIsInJvbGVzIjpbIlVTRVIiLCJBRE1JTiIsIlNVUEVSQURNSU4iXSwicHJvZmlsZSI6eyJpZCI6MiwiZmlyc3RfbmFtZSI6InN1cGVyYXBhYW5zaSIsImxhc3RfbmFtZSI6IkRlZmF1bHQiLCJwcm9maWxlX3BpY3R1cmUiOm51bGwsIm5vX2hwIjoibnVsbCIsInN0YXR1cyI6IlNVUEVSQURNSU4iLCJwaWN0dXJlSWQiOm51bGwsInVzZXJJZCI6NX0sImlhdCI6MTcxMTczMzMzNiwiZXhwIjoxNzExODE5NzM2fQ.XwxB3X8yJdF9WBaKG2G5n0OGgKq7zFRR-eCkAU5bVIU

{
  "email": "admin02@gmail.com", 
  "password": "123123", 
  "nama": "admin3"
}

### Login admin
# POST /api/v1/auth/login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin02@gmail.com", 
  "password": "123123"
}

###get all user (fitur admin dengan token admin)
GET http://localhost:3000/api/v1/auth/getAlluser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InN1cnlhIiwiZW1haWwiOiJzdXJ5YUBnbWFpbC5jb20iLCJyb2xlcyI6WyJVU0VSIl0sInByb2ZpbGUiOnsiaWQiOjEsImZpcnN0X25hbWUiOiJzdXJ5YSIsImxhc3RfbmFtZSI6IkRlZmF1bHQiLCJwcm9maWxlX3BpY3R1cmUiOm51bGwsIm5vX2hwIjoiMDk4MTI3Iiwic3RhdHVzIjoibWFoYXNpc3dhIiwicGljdHVyZUlkIjpudWxsLCJ1c2VySWQiOjF9LCJpYXQiOjE3MTE5MzU5NDMsImV4cCI6MTcxMjAyMjM0M30._5hU4BuDIaIy-lEZye8AsIpE3nDwNwcs74GeuVeoxL0

###get profile
GET http://localhost:3000/api/v1/auth/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsIm5hbWUiOiJ1c2VyMSIsImVtYWlsIjoic3VyeWF5QGdtYWlsLmNvbSIsInJvbGVzIjpbIlVTRVIiXSwicHJvZmlsZSI6eyJpZCI6MTMsImZpcnN0X25hbWUiOiJzdXJ5YWN1YWtzIiwibGFzdF9uYW1lIjoiRGVmYXVsdCIsInByb2ZpbGVfcGljdHVyZSI6Imh0dHBzOi8vaWsuaW1hZ2VraXQuaW8vamVuaXJpc2thLzE3MTIwNDM4NDAxNTNfZUJYUTY1NTdILmpwZWciLCJub19ocCI6IjA4MTI4MTgyMSIsInN0YXR1cyI6Im1haGFzaXN3YSIsInBpY3R1cmVJZCI6IjIyM2IyMGU2YzcyOTYwZDY4ZGMwYmYwYjU2ZGEyZDRkNzgwMzNlZjYxMWU5YTRjNzI4ODIxM2NhNmZmZDlhZjMiLCJ1c2VySWQiOjEzfSwiaWF0IjoxNzEyMDcxNjMyLCJleHAiOjE3MTIxNTgwMzJ9.2j6DqgVCtPuGO0etyjwzoolgIeHi2eXxkUM3KhYAWeI

###Membuat kategori Baru
# POST /api/v1/kategori/add
POST https://insight-hub-api.vercel.app/api/v1/kategori/add
Content-Type: application/json

{
    "nama": "Sistem Informasi",
    "deskripsi": "Artikel-artikel tentang pikiran buatan"
}

###Mengambil semua kategori
# GET /api/v1/kategori/get-all
GET https://insight-hub-api.vercel.app/api/v1/kategori/get-all

###DELETE kategori
# DELETE /api/v1/kategori/delete/:id
DELETE https://insight-hub-api.vercel.app/api/v1/kategori/delete/1




###Membuat Artikel Baru (POST)
# POST /api/v1/artikel/add
POST https://insight-hub-api.vercel.app/api/v1/artikel/upload
Content-Type:application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InN1cnlhIiwiZW1haWwiOiJzdXJ5YUBnbWFpbC5jb20iLCJyb2xlcyI6WyJVU0VSIl0sInByb2ZpbGUiOnsiaWQiOjEsImZpcnN0X25hbWUiOiJzdXJ5YSIsImxhc3RfbmFtZSI6IkRlZmF1bHQiLCJwcm9maWxlX3BpY3R1cmUiOm51bGwsIm5vX2hwIjoiMDk4MTI3Iiwic3RhdHVzIjoibWFoYXNpc3dhIiwicGljdHVyZUlkIjpudWxsLCJ1c2VySWQiOjF9LCJpYXQiOjE3MTE5NDkxMTYsImV4cCI6MTcxMjAzNTUxNn0.U4VKUEp2YJAd0b2anM9BtEtEFvHRSJXE25YXl7hVeqI
 
{
  "judul": "okse",
  "deskripsi": "Deskripsi lengkap dari artikel",
  "link": "http://contohlink.com",
  "gambar_artikel": "{sertakan gambar/upload} ",
  "kategoriId": 1,
  "kategoriId":2
}

###Mengambil Semua Artikel (GET)
# GET /api/v1/artikel/get-all
GET https://insight-hub-api.vercel.app/api/v1/artikel/get-all

#### 1. Update Artikel (Request dengan Token)
# PUT https://insight-hub-api.vercel.app/api/v1/artikel/updateArtikel/{:idArtikel}
PUT https://insight-hub-api.vercel.app/api/v1/artikel/updateArtikel/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqZW5pLnJpc2thQGdtYWlsLmNvbSIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNzExNDY1OTUwLCJleHAiOjE3MTE1NTIzNTB9.1quHOrWjV1Hr4RL59I71PN6Ny4gunZWrj-Bj_x36j-o

{
  "judul": "ganti2",
  "deskripsi": "Deskripsi artikel baru",
  "link": "https://example.com",
  "kategoriId": 1,
  "gambar_artikel": ""
  
}
###DELETE ARTIKEL 
# DELETE /api/v1/artikel/delete/:id
DELETE http://localhost:3000/api/v1/artikel/deleteArtikel/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InN1cnlhIiwiZW1haWwiOiJzdXJ5YUBnbWFpbC5jb20iLCJyb2xlcyI6WyJVU0VSIl0sInByb2ZpbGUiOnsiaWQiOjEsImZpcnN0X25hbWUiOiJzdXJ5YSIsImxhc3RfbmFtZSI6IkRlZmF1bHQiLCJwcm9maWxlX3BpY3R1cmUiOm51bGwsIm5vX2hwIjoiMDk4MTI3Iiwic3RhdHVzIjoibWFoYXNpc3dhIiwicGljdHVyZUlkIjpudWxsLCJ1c2VySWQiOjF9LCJpYXQiOjE3MTE5NDkxMTYsImV4cCI6MTcxMjAzNTUxNn0.U4VKUEp2YJAd0b2anM9BtEtEFvHRSJXE25YXl7hVeqI



# Mencari Artikel
# /api/v1/artikel/search?:param=key

# example
###Mencari Artikel Berdasarkan Kategori
GET https://insight-hub-api.vercel.app/api/v1/search-artikel/search?kategori=Teknologi

###Mencari Artikel Berdasarkan Judul
GET https://insight-hub-api.vercel.app/api/v1/search-artikel/search?judul=ok

###Mencari Artikel Berdasarkan AuthorId
GET https://insight-hub-api.vercel.app/api/v1/search-artikel/search?authorId=1

###Mencari Artikel Berdasarkan ArtikelId
GET https://insight-hub-api.vercel.app/api/v1/search-artikel/search?artikelId=6



### Menyimpan Artikel
# POST /api/v1/artikel/save/{artikelId}
# POST https://insight-hub-api.vercel.app/api/v1/artikel/save/{artikelId}
# Authorization: Bearer <token didapat saat login user dan token akan nonAktif > 1 days
# POST https://insight-hub-api.vercel.app/api/v1/artikel/save/1
POST https://insight-hub-api.vercel.app/api/v1/artikel/save/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6InVzZXIxIiwiZW1haWwiOiJqZW5pLnJpc2thYUBnbWFpbC5jb20iLCJyb2xlcyI6WyJVU0VSIl0sImlhdCI6MTcxMTUyNjk3MCwiZXhwIjoxNzExNjEzMzcwfQ.VWGMlr9QsffuR6lv_et_OnU4o5bqE5WLRjJLcwkBmV4

### Mendapatkan Artikel yang Disimpan oleh Pengguna
# GET /api/v1/artikel/saved
# Authorization: Bearer <token didapat saat login user dan token akan nonAktif > 1 days
# GET https://insight-hub-api.vercel.app/api/v1/artikel/saved
GET https://insight-hub-api.vercel.app/api/v1/artikel/saved
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6InVzZXIxIiwiZW1haWwiOiJqZW5pLnJpc2thYUBnbWFpbC5jb20iLCJyb2xlcyI6WyJVU0VSIl0sImlhdCI6MTcxMTUyNjk3MCwiZXhwIjoxNzExNjEzMzcwfQ.VWGMlr9QsffuR6lv_et_OnU4o5bqE5WLRjJLcwkBmV4

### Memberikan Rating pada Artikel
# Gantikan {artikelId} dengan ID artikel yang ingin diberi rating dan isi nilai dengan nilai rating (1-5).
# Authorization: Bearer <token didapat saat login user dan token akan nonAktif > 1 days
# POST https://insight-hub-api.vercel.app/api/v1/artikel/rating/{artikelId}
POST https://insight-hub-api.vercel.app/api/v1/artikel/rate/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6InVzZXIxIiwiZW1haWwiOiJqZW5pLnJpc2thYWFhQGdtYWlsLmNvbSIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNzExNTI3NTk5LCJleHAiOjE3MTE2MTM5OTl9.7en1DQMMFCyFl2Sa_71TvuWRXWd_KAPNxomZ00ux6cI

{
  "nilai": 3
}

### Melaporkan Artikel
# Gantikan {artikelId} dengan ID artikel yang ingin dilaporkan dan isi alasan dengan alasan pelaporan.
# POST https://insight-hub-api.vercel.app/api/v1/artikel/report/{artikelId}
POST https://insight-hub-api.vercel.app/api/v1/artikel/report/1
Content-Type: application/json
# Authorization: Bearer <token didapat saat login user dan token akan nonAktif > 1 days
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6InVzZXIxIiwiZW1haWwiOiJqZW5pLnJpc2thYWFhQGdtYWlsLmNvbSIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNzExNTI4MjQyLCJleHAiOjE3MTE2MTQ2NDJ9.Avn5bIKEqtpE8RPhK1qn7-hEzPwhf4kdfDU6DW4Tjkg

{
  "alasan": "Isi alasan pelaporan di sini"
}
