# Base Url = https://insight-hub-api.vercel.app

### regis user
# POST /api/v1/auth/register/user
# POST http://localhost:3000/api/v1/auth/register/user
POST https://insight-hub-api.vercel.app/api/v1/auth/register/user
Content-Type: application/json

{
  "email":"oke@gmail.com", 
  "password":"123123", 
  "nama":"user1",
  "no_hp":"081281821",
  "status":"ok"
}

### Login user
# POST /api/v1/auth/login 
POST https://insight-hub-api.vercel.app/api/v1/auth/login
Content-Type: application/json

{
  "email":"surya@gmail.com",  
  "password": "123123"
}

### forgot password
POST https://insight-hub-api.vercel.app/api/v1/auth/forgotPassword
Content-Type: application/json

{
    "email": "jeni.riska@gmail.com"
}


### change password
# POST /api/v1/auth/change-password?token={link email params}
POST https://insight-hub-api.vercel.app/api/v1/auth/change-password?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqZW5pLnJpc2thYUBnbWFpbC5jb20iLCJpYXQiOjE3MTEyNzQ0NTksImV4cCI6MTcxMTI3ODA1OX0.8DutF9Lu5WdR-sQ_Pv9jzVmhz-To6U1JqRjkxu06BOQ
Content-Type: application/json

{
  "password":"user12345",
  "confirm_password":"user12345"
}

### regis SUPERADMIN
# POST /api/v1/auth/register/su
POST http://localhost:3000/api/v1/auth/register/su
Content-Type: application/json

{
  "email":"supery@gmail.com", 
  "password":"123123", 
  "nama":"superapaansi"
}

### Login SUPER ADMIN
# POST /api/v1/auth/login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "supery@gmail.com", 
  "password": "123123"
}



### regis admin
# POST /api/v1/auth/register/admin
POST http://localhost:3000/api/v1/auth/register/admin
Content-Type: application/json
# Authorization: Bearer <token didapat saat login dengan superUser dan token akan nonAktif > 1 days
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6InN1cGVyYXBhYW5zaSIsImVtYWlsIjoic3VwZXJ5QGdtYWlsLmNvbSIsInJvbGVzIjpbIlVTRVIiLCJBRE1JTiIsIlNVUEVSQURNSU4iXSwicHJvZmlsZSI6eyJpZCI6MiwiZmlyc3RfbmFtZSI6InN1cGVyYXBhYW5zaSIsImxhc3RfbmFtZSI6IkRlZmF1bHQiLCJwcm9maWxlX3BpY3R1cmUiOm51bGwsIm5vX2hwIjoibnVsbCIsInN0YXR1cyI6IlNVUEVSQURNSU4iLCJwaWN0dXJlSWQiOm51bGwsInVzZXJJZCI6NX0sImlhdCI6MTcxMTczMzMzNiwiZXhwIjoxNzExODE5NzM2fQ.XwxB3X8yJdF9WBaKG2G5n0OGgKq7zFRR-eCkAU5bVIU

{
  "email": "admin02@gmail.com", 
  "password": "123123", 
  "nama": "admin3"
}

### Login admin
# POST /api/v1/auth/login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin02@gmail.com", 
  "password": "123123"
}

###get all user
GET http://localhost:3000/api/v1/auth/getAlluser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwibmFtZSI6ImFkbWluMyIsImVtYWlsIjoiYWRtaW4wMkBnbWFpbC5jb20iLCJyb2xlcyI6WyJVU0VSIiwiQURNSU4iXSwicHJvZmlsZSI6eyJpZCI6NCwiZmlyc3RfbmFtZSI6ImFkbWluMyIsImxhc3RfbmFtZSI6IkRlZmF1bHQiLCJwcm9maWxlX3BpY3R1cmUiOm51bGwsIm5vX2hwIjoibnVsbCIsInN0YXR1cyI6IkFETUlOIiwicGljdHVyZUlkIjpudWxsLCJ1c2VySWQiOjh9LCJpYXQiOjE3MTE3MzM2NTIsImV4cCI6MTcxMTgyMDA1Mn0.yiL0_p2p0ZkGg_PTcOloEiJherzaKP7Nizfjrg7K7f0

###get profile
GET http://localhost:3000/api/v1/auth/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwibmFtZSI6InVzZXIxIiwiZW1haWwiOiJwaXBvb3VAZ21haWwuY29tIiwicm9sZXMiOlsiVVNFUiJdLCJwcm9maWxlIjp7ImlkIjo1LCJmaXJzdF9uYW1lIjoidXNlcjEiLCJsYXN0X25hbWUiOiJEZWZhdWx0IiwicHJvZmlsZV9waWN0dXJlIjpudWxsLCJub19ocCI6IjA4MTI4MTgyMSIsInN0YXR1cyI6Im9rIiwicGljdHVyZUlkIjpudWxsLCJ1c2VySWQiOjl9LCJpYXQiOjE3MTE3MzM4NTAsImV4cCI6MTcxMTgyMDI1MH0.egm9p5JdbmEob24pAs7U-S5LHLFjXut_2w5p9CRFpe0

###Membuat kategori Baru
# POST /api/v1/kategori/add
POST https://insight-hub-api.vercel.app/api/v1/kategori/add
Content-Type: application/json

{
    "nama": "Sistem pikir",
    "deskripsi": "Artikel-artikel tentang pikiran buatan"
}

###Mengambil semua kategori
# GET /api/v1/kategori/get-all
GET https://insight-hub-api.vercel.app/api/v1/kategori/get-all

###DELETE kategori
# DELETE /api/v1/kategori/delete/:id
DELETE https://insight-hub-api.vercel.app/api/v1/kategori/delete/1




###Membuat Artikel Baru (POST)
# POST /api/v1/artikel/add
POST https://insight-hub-api.vercel.app/api/v1/artikel/upload
Content-Type:application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InVzZXIxIiwiZW1haWwiOiJva2VAZ21haWwuY29tIiwicm9sZXMiOlsiVVNFUiJdLCJwcm9maWxlIjp7ImlkIjoxLCJmaXJzdF9uYW1lIjoidXNlcjEiLCJsYXN0X25hbWUiOiJEZWZhdWx0IiwicHJvZmlsZV9waWN0dXJlIjpudWxsLCJub19ocCI6IjA4MTI4MTgyMSIsInN0YXR1cyI6Im9rIiwicGljdHVyZUlkIjpudWxsLCJ1c2VySWQiOjF9LCJpYXQiOjE3MTE4NDQ4OTgsImV4cCI6MTcxMTkzMTI5OH0.2uLTlEZsvHzN--dBVzXIOlydIfHhPNNm7qtE6AVRMlk
 
{
  "judul": "okse",
  "deskripsi": "Deskripsi lengkap dari artikel",
  "link": "http://contohlink.com",
  "gambar_artikel": "{sertakan gambar/upload} ",
  "kategoriId": 1
}

###Mengambil Semua Artikel (GET)
# GET /api/v1/artikel/get-all
GET https://insight-hub-api.vercel.app/api/v1/artikel/get-all

#### 1. Update Artikel (Request dengan Token)
# PUT https://insight-hub-api.vercel.app/api/v1/artikel/updateArtikel/{:idArtikel}
PUT https://insight-hub-api.vercel.app/api/v1/artikel/updateArtikel/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqZW5pLnJpc2thQGdtYWlsLmNvbSIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNzExNDY1OTUwLCJleHAiOjE3MTE1NTIzNTB9.1quHOrWjV1Hr4RL59I71PN6Ny4gunZWrj-Bj_x36j-o

{
  "judul": "ganti2",
  "deskripsi": "Deskripsi artikel baru",
  "link": "https://example.com",
  "kategoriId": 1,
  "gambar_artikel": ""
  
}
###DELETE ARTIKEL 
# DELETE /api/v1/artikel/delete/:id
DELETE http://localhost:3000/api/v1/artikel/deleteArtikel/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwibmFtZSI6InN1cGVyYXBhYW5zaSIsImVtYWlsIjoic3VwZXJ5QGdtYWlsLmNvbSIsInJvbGVzIjpbIlVTRVIiLCJBRE1JTiIsIlNVUEVSQURNSU4iXSwicHJvZmlsZSI6eyJpZCI6MiwiZmlyc3RfbmFtZSI6InN1cGVyYXBhYW5zaSIsImxhc3RfbmFtZSI6IkRlZmF1bHQiLCJwcm9maWxlX3BpY3R1cmUiOm51bGwsIm5vX2hwIjoibnVsbCIsInN0YXR1cyI6IlNVUEVSQURNSU4iLCJwaWN0dXJlSWQiOm51bGwsInVzZXJJZCI6NX0sImlhdCI6MTcxMTczMzMzNiwiZXhwIjoxNzExODE5NzM2fQ.XwxB3X8yJdF9WBaKG2G5n0OGgKq7zFRR-eCkAU5bVIU



# Mencari Artikel
# /api/v1/artikel/search?:param=key

# example
###Mencari Artikel Berdasarkan Kategori
GET https://insight-hub-api.vercel.app/api/v1/search-artikel/search?kategori=Teknologi

###Mencari Artikel Berdasarkan Judul
GET https://insight-hub-api.vercel.app/api/v1/search-artikel/search?judul=ok

###Mencari Artikel Berdasarkan AuthorId
GET https://insight-hub-api.vercel.app/api/v1/search-artikel/search?authorId=1


### Menyimpan Artikel
# POST /api/v1/artikel/save/{artikelId}
# POST https://insight-hub-api.vercel.app/api/v1/artikel/save/{artikelId}
# Authorization: Bearer <token didapat saat login user dan token akan nonAktif > 1 days
# POST https://insight-hub-api.vercel.app/api/v1/artikel/save/1
POST https://insight-hub-api.vercel.app/api/v1/artikel/save/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6InVzZXIxIiwiZW1haWwiOiJqZW5pLnJpc2thYUBnbWFpbC5jb20iLCJyb2xlcyI6WyJVU0VSIl0sImlhdCI6MTcxMTUyNjk3MCwiZXhwIjoxNzExNjEzMzcwfQ.VWGMlr9QsffuR6lv_et_OnU4o5bqE5WLRjJLcwkBmV4

### Mendapatkan Artikel yang Disimpan oleh Pengguna
# GET /api/v1/artikel/saved
# Authorization: Bearer <token didapat saat login user dan token akan nonAktif > 1 days
# GET https://insight-hub-api.vercel.app/api/v1/artikel/saved
GET https://insight-hub-api.vercel.app/api/v1/artikel/saved
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6InVzZXIxIiwiZW1haWwiOiJqZW5pLnJpc2thYUBnbWFpbC5jb20iLCJyb2xlcyI6WyJVU0VSIl0sImlhdCI6MTcxMTUyNjk3MCwiZXhwIjoxNzExNjEzMzcwfQ.VWGMlr9QsffuR6lv_et_OnU4o5bqE5WLRjJLcwkBmV4

### Memberikan Rating pada Artikel
# Gantikan {artikelId} dengan ID artikel yang ingin diberi rating dan isi nilai dengan nilai rating (1-5).
# Authorization: Bearer <token didapat saat login user dan token akan nonAktif > 1 days
# POST https://insight-hub-api.vercel.app/api/v1/artikel/rating/{artikelId}
POST https://insight-hub-api.vercel.app/api/v1/artikel/rate/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6InVzZXIxIiwiZW1haWwiOiJqZW5pLnJpc2thYWFhQGdtYWlsLmNvbSIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNzExNTI3NTk5LCJleHAiOjE3MTE2MTM5OTl9.7en1DQMMFCyFl2Sa_71TvuWRXWd_KAPNxomZ00ux6cI

{
  "nilai": 3
}

### Melaporkan Artikel
# Gantikan {artikelId} dengan ID artikel yang ingin dilaporkan dan isi alasan dengan alasan pelaporan.
# POST https://insight-hub-api.vercel.app/api/v1/artikel/report/{artikelId}
POST https://insight-hub-api.vercel.app/api/v1/artikel/report/1
Content-Type: application/json
# Authorization: Bearer <token didapat saat login user dan token akan nonAktif > 1 days
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6InVzZXIxIiwiZW1haWwiOiJqZW5pLnJpc2thYWFhQGdtYWlsLmNvbSIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNzExNTI4MjQyLCJleHAiOjE3MTE2MTQ2NDJ9.Avn5bIKEqtpE8RPhK1qn7-hEzPwhf4kdfDU6DW4Tjkg

{
  "alasan": "Isi alasan pelaporan di sini"
}
